stages:
- name: publish catalog tag
  steps:
  - publishCatalogConfig:
      path: ./chart
      catalogTemplate: test
      version: 0.0.1
      gitUrl: https://github.com:443/axeal/axe.al.git
      gitBranch: master
      gitAuthor: alex
      gitEmail: alex@example.com
    envFrom:
    - sourceName: github-credentials
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: github-credentials
      sourceKey: PASSWORD
      targetKey: PASSWORD
branch:
  include:
  - pipeline
  exclude:
  - master
