stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - pipeline
  exclude:
  - master
