stages:
- name: publish catalog
  steps:
  - publishCatalogConfig:
      path: ./chart
      catalogTemplate: ${CICD_GIT_REPO_NAME}
      version: 0.0.4
      gitUrl: ${TEMPLATE_NAME}
      gitBranch: master
      gitAuthor: alex
      gitEmail: alex@example.com
    env:
      TEMPLATE_NAME: git@github.com:axeal/test-catalog.git
    envFrom:
    - sourceName: publish-key
      sourceKey: DEPLOY_KEY
branch:
  include:
  - pipeline
  exclude:
  - master
