stages:
- name: publish catalog
  steps:
  - publishCatalogConfig:
      path: ./chart
      catalogTemplate: ${TEMPLATE_NAME}
      version: 0.0.4
      gitUrl: git@github.com:axeal/test-catalog.git
      gitBranch: master
      gitAuthor: alex
      gitEmail: alex@example.com
    env:
      TEMPLATE_NAME: foo
    envFrom:
    - sourceName: publish-key
      sourceKey: DEPLOY_KEY
branch:
  include:
  - pipeline
  exclude:
  - master
