stages:
- name: Deploy App
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:test-test
      version: 0.0.4
      name: nginx
      targetNamespace: default
branch:
  include:
  - pipeline
  exclude:
  - master
