stages:
- name: Cluster Level
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:test-test
      version: 0.0.3
      name: cluster
      targetNamespace: default
- name: Project Level
  steps:
  - applyAppConfig:
      catalogTemplate: p-dkq27:test-test
      version: 0.0.3
      name: project
      targetNamespace: default
branch:
  include:
  - pipeline
  exclude:
  - master
