stages:
- name: Build
  steps:
  - runScriptConfig:
      image: python:2.7-stretch
      shellScript: |-
        git submodule update --init --recursive
        wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
        dpkg -i hugo*.deb
        pip install Pygments
        hugo
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test:latest
      pushRemote: true
      registry: registry.alexseymour.co.uk:8443
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - pipeline
  exclude:
  - master
