sudo: required

services:
  - docker

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
  - hugo
  - docker build . -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_TAG

deploy:
  provider: script
  script: bash docker_push.sh
