
kind: Service
apiVersion: v1
metadata:
  name: blog
spec:
  selector:
    app: blog
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: blog
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
          - containerPort: 80
